### ISSUE TITLE
Possibly wrong 'reverse' implementation 

### ISSUE THREAD

**Issue by inobelar** [kostakis/Generic-Queue#4]
Current sources describes 'data' (also typically named as queue 'node') and 'reverse' as:

https://github.com/kostakis/Generic-Queue/blob/ad5e5f1e02ff984e85c313efb4ca8cd2c0ad1c4b/src/queue.c#L5-L8

https://github.com/kostakis/Generic-Queue/blob/ad5e5f1e02ff984e85c313efb4ca8cd2c0ad1c4b/src/queue.c#L92-L104

Since `enqueue`  mem-copy passed 'data' into 'node' data, and `dequeue` mem-copy 'node' data into outer scope, `reverse` function must have pre-allocation for it:

```cpp
queue *reverse(queue *q) {
  if (q == NULL)
    return NULL;
  if (q->size == 0)
    return q; /* Nothing to reverse */
  else {
    void* temp_data = malloc(q->allocationSize);
    if(temp_data != NULL)
    {
      dequeue(q, temp_data); /* extract last 'node' data */
      reverse(q);            /* recursion */
      enqueue(q, temp_data); /* insert last 'node' data as first */
      
      free(temp_data);
    }
    return q;
  }
}
```

I'm possibly be wrong with assumptions above, but it looks strange, that `dequeue` outputs 'node' data **not** into some 'void* data', but into 'data' type (aka 'node').

**Comment by kostakis** [comment]
Hi @inobelar 

First of all thanks for your contributions to the repository!
Indeed you are 100% correct of this.
I wonder how the reverse function works, maybe we have small objects and copying the data does not break other data.
I will implemented your suggested fix and also change the variables names to data and node, before it was really confusing.
